### ISSUE TITLE
в дев ветке чет всё съехало

### ISSUE THREAD

**Issue by MaxFix** [DaniilSmirnov/APKInstaller#9]
<img width="736" alt="Снимок экрана 2021-04-20 в 00 46 03" src="https://user-images.githubusercontent.com/23189095/115307379-c9908480-a171-11eb-996a-7cc189929335.png">

**Comment by MaxFix** [comment]
Странно, что повторилось только 1 раз, закрываю до лучших времен

**Comment by DaniilSmirnov** [comment]
Нашел и поправил кста
